export const CONTACT_LIST_FRIEND = "LIST_F";
export const CONTACT_LIST_GROUP = "LIST_G";
export const CONTACT_LIST_FRIEND_REQUEST= "LIST_FR";
export const SETTING_PROFILE = "SETTING_PROFILE";
export const SETTING_ACCOUNT = "SETTING_ACCOUNT"; /*  */
export const SETTING_DISPLAY = "SETTING_DISPLAY";
export const VIEW_CHAT = "VIEW_CHAT";
export const VIEW_CONTACT = "VIEW_CONTACT";
export const VIEW_NOTI = "VIEW_NOTIFICATION";

